---
- name: Attempting to overlay cronie hourly and sysconfig configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart crond
  with_items:
    - { src: 0hourly.j2, dst: /etc/cron.d/0hourly, mode: '0644' }
    - { src: crond.sysconfig.j2, dst: /etc/sysconfig/crond, mode: '0600' }

- name: Attempting to overlay cron.allow configurations
  template:
    src: cron.allow.j2
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0600
  notify: restart crond

- name: Attempting to overlay cron.deny configurations
  template:
    src: cron.deny.j2
    dest: /etc/cron.deny
    owner: root
    group: root
    mode: 0600
  notify: restart crond
...
