---
- name: Ensure that the cronie package is installed
  tags: cronie
  become: true
  yum:
    name: cronie
    state: present

- name: Attempting to overlay cronie configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: restart crond
  loop:
    - { src: 0hourly.j2, dst: /etc/cron.d/0hourly, mode: '0644' }
    - { src: cron.allow.j2, dst: /etc/cron.allow, mode: '0600' }
    - { src: cron.deny.j2, dst: /etc/cron.deny, mode: '0600' }
    - { src: crond.sysconfig.j2, dst: /etc/sysconfig/crond, mode: '0600' }
  loop_control:
    label: "{{ item.dst|basename }}"

- name: Attempting to overlay system cronjob environment variables, if applicable
  cron:
    cron_file: "{{ item.0.cron_file }}"
    env: yes
    insertafter: "{{ item.1.insertafter|default(omit) }}"
    insertbefore: "{{ item.1.insertbefore|default(omit) }}"
    name: "{{ item.1.name|upper }}"
    user: "{{ item.1.user|default('root') }}"
    value: "{{ item.1.value }}"
  notify: restart crond
  loop: "{{ cronie_system|subelements('environment') }}"
  loop_control:
    label: "{{ item.0.cron_file }}"
  when:
    - cronie_system|length > 0
    - item.0.cron_file is defined
    - item.1.name is defined
    - item.1.value is defined

- name: Attempting to overlay system cronjob commands, if applicable
  cron:
    cron_file: "{{ item.0.cron_file }}"
    day: "{{ item.1.day|default(omit) }}"
    disabled: "{{ item.1.disabled|default(omit) }}"
    env: no
    hour: "{{ item.1.hour|default(omit) }}"
    job: "{{ item.1.job }}"
    minute: "{{ item.1.minute|default(omit) }}"
    month: "{{ item.1.month|default(omit) }}"
    name: "{{ item.1.name }}"
    special_time: "{{ item.1.special_time|default(omit) }}"
    state: "{{ item.1.state|default(omit) }}"
    user: "{{ item.1.user|default('root') }}"
    weekday: "{{ item.1.weekday|default(omit) }}"
  notify: restart crond
  loop: "{{ cronie_system|subelements('commands') }}"
  loop_control:
    label: "{{ item.0.cron_file }}"
  when:
    - cronie_system|length > 0
    - item.0.cron_file is defined
    - item.1.job is defined
    - item.1.name is defined

- name: Attempting to apply permissions on system crontab files
  file:
    path: "{{ '/etc/cron.d/' + item.cron_file }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default(0644) }}"
  loop: "{{ cronie_system }}"
  loop_control:
    label: "{{ item.cron_file }}"
  when:
    - cronie_system|length > 0
    - item.cron_file is defined

- name: Attempting to overlay user cronjob environment variables, if applicable
  cron:
    env: yes
    insertafter: "{{ item.1.insertafter|default(omit) }}"
    insertbefore: "{{ item.1.insertbefore|default(omit) }}"
    name: "{{ item.1.name|upper }}"
    user: "{{ item.0.user }}"
    value: "{{ item.1.value }}"
  notify: restart crond
  loop: "{{ cronie_user|subelements('environment') }}"
  loop_control:
    label: "{{ item.0.user }}"
  when:
    - cronie_user|length > 0
    - item.0.user is defined
    - item.1.name is defined
    - item.1.value is defined

- name: Attempting to overlay user cronjob commands, if applicable
  cron:
    day: "{{ item.1.day|default(omit) }}"
    disabled: "{{ item.1.disabled|default(omit) }}"
    env: no
    hour: "{{ item.1.hour|default(omit) }}"
    job: "{{ item.1.job }}"
    minute: "{{ item.1.minute|default(omit) }}"
    month: "{{ item.1.month|default(omit) }}"
    name: "{{ item.1.name }}"
    special_time: "{{ item.1.special_time|default(omit) }}"
    state: "{{ item.1.state|default(omit) }}"
    user: "{{ item.0.user }}"
    weekday: "{{ item.1.weekday|default(omit) }}"
  notify: restart crond
  loop: "{{ cronie_user|subelements('commands') }}"
  loop_control:
    label: "{{ item.0.user }}"
  when:
    - cronie_user|length > 0
    - item.0.user is defined
    - item.1.job is defined
    - item.1.name is defined

- name: Enable and start the crond service on boot
  tags: cronie
  become: true
  service:
    enabled: yes
    name: crond
    state: started
...
