---
- name: Install cronie
  tags: cronie
  yum:
    name=cronie
    state=latest
    update_cache=yes
  register: cronie_yum

- block:
    - name: Configure cronie 
      template: src={{ item.src }}
                dest={{ item.dst }}
                owner=root
                group=root
                mode={{ item.mode }}
      notify: restart crond
      with_items:
        - { src: 0hourly.j2, dst: /etc/cron.d/0hourly, mode: '0644' }
        - { src: cron.deny.j2, dst: /etc/cron.deny, mode: '0644' }
        - { src: crond.sysconfig.j2, dst: /etc/sysconfig/crond, mode: '0600' }
    - name: Configure cronie jobs
      template: src=cronie.j2
                dest={{ item.dest }}
                owner=root
                group=root
                mode=0644
      notify: restart crond
      with_items: "{{ cronie_jobs }}"
      when:
        - item.dest is defined
        - item.jobs is defined
    - name: Enable and start crond
      service: name=crond
               enabled=yes
               state=started
  tags: cronie
  when: cronie_yum|success
