---
- name: Ensure that the cronie package is installed
  tags: cronie
  become: true
  yum:
    name: cronie
    state: present
  register: cronie_yum

- block:
    - name: Executing tasks via cronie task list (etc)
      import_tasks: cronie_etc.yml

    - name: Executing tasks via cronie task list (system)
      import_tasks: cronie_system.yml
      when:
        - cronie_system is defined
        - cronie_system|length > 0

    - name: Executing tasks via cronie task list (user)
      import_tasks: cronie_user.yml
      when:
        - cronie_user is defined
        - cronie_user|length > 0

    - name: Enable and start the crond service on boot
      service:
        enabled: yes
        name: crond
        state: started
  tags: cronie
  become: true
  when: cronie_yum|success
...
