---
- name: Ensure that the cronie package is installed
  tags: cronie
  become: true
  yum:
    name: cronie
    state: present
  register: cronie_yum

- name: Attempting to import cronie related tasks
  tags: cronie
  become: true
  block:
    - import_tasks: cronie_etc.yml
    - import_tasks: cronie_system.yml
    - import_tasks: cronie_user.yml
  when: cronie_yum is success

- name: Enable and start the crond service on boot
  tags: cronie
  become: true
  service:
    enabled: yes
    name: crond
    state: started
  when: cronie_yum is success
...
